using Unity.Burst;
using Unity.Collections;
using Unity.Jobs;
using UnityEngine;

namespace Kira.Hashing
{
    public class HashVisualization : MonoBehaviour
    {
        private static int hashesId = Shader.PropertyToID("_Hashes");
        private static int configId = Shader.PropertyToID("_Config");

        [SerializeField]
        private Mesh instanceMesh;

        [SerializeField]
        private Material material;

        [SerializeField, Range(1, 512)]
        private int resolution = 16;

        private NativeArray<uint> hashes;

        private ComputeBuffer hashesBuffer;

        private MaterialPropertyBlock propertyBlock;


        private void OnEnable()
        {
            int length = resolution * resolution;
            hashes = new NativeArray<uint>(length, Allocator.Persistent);
            hashesBuffer = new ComputeBuffer(length, 4);

            new HashJob
            {
                hashes = hashes
            }.ScheduleParallel(hashes.Length, resolution, default).Complete();

            hashesBuffer.SetData(hashes);

            propertyBlock ??= new MaterialPropertyBlock();
            propertyBlock.SetBuffer(hashesId, hashesBuffer);
            propertyBlock.SetVector(configId, new Vector4(resolution, 1f / resolution));
        }

        private void OnDisable()
        {
            hashes.Dispose();
            hashesBuffer.Release();
            hashesBuffer = null;
        }

        private void OnValidate()
        {
            if (hashesBuffer != null && enabled)
            {
                OnDisable();
                OnEnable();
            }
        }

        private void Update()
        {
            Graphics.DrawMeshInstancedProcedural(
                instanceMesh, 0, material, new Bounds(Vector3.zero, Vector3.one
                ), hashes.Length, propertyBlock
            );
        }

        [BurstCompile(FloatPrecision.Standard, FloatMode.Fast, CompileSynchronously = true)]
        private struct HashJob : IJobFor
        {
            [WriteOnly]
            public NativeArray<uint> hashes;

            public void Execute(int i)
            {
                hashes[i] = (uint)i;
            }
        }
    }
}